### ISSUE TITLE
Is there any plan to add aiohttp support?

### ISSUE THREAD

**Issue by amenezes** [SolarEdgeTech/pyctuator#17]
First thanks for this project :+1: 

I would like to check if there's something in the project roadmap to add [aiohttp](https://aiohttp.readthedocs.io) support? Or maybe can I contribute with a PR. It's ok?

**Comment by MatanRubin** [comment]
We were waiting for some feedback from the community before we decide which frameworks to support next.
aiohttp looks like a great candidate and adding it should be relatively simple.
It would be great if you could submit an initial PR and once the foundation is there the rest of the team could help fine-tune it.

**Comment by michaelyaakoby** [comment]
Thanks @amenezes for asking and for contributing the aiohttp support - everything is now ready in #19 .
We'll merge soon.

**Comment by michaelyaakoby** [comment]
Done, thank you all
