### ISSUE TITLE
Do you support Tornado Web Server？

### ISSUE THREAD

**Issue by lyhu** [SolarEdgeTech/pyctuator#34]
Do you support Tornado Web Server？

**Comment by michaelyaakoby** [comment]
Hi @lyhu, so far we weren't planning to add support for Tornado.
And sicne we aren't familiar with Tornado, it will help a lot if you can create a PR with at least some basic implementation and an example for using it.
I would start with creating a Tornado example `pyctuator/examples/torando/` (similar to the aiohttp example), next you can implemet pyctuator/pyctuator/impl/tornado_pyctuator.py (imilar to `pyctuator/pyctuator/impl/aiohttp_pyctuator.py`).
Once you've started, send a PR and I'll review and fix what's needed.
Thanks,
Michael

**Comment by michaelyaakoby** [comment]
Done, please use version 0.13.1.
Thanks again @lyhu for asking and @aneasystone for the pull request.
