### ISSUE TITLE
https support

### ISSUE THREAD

**Issue by PvanHengel** [SolarEdgeTech/pyctuator#41]
Good Morning,

Now that I got this up and running with the correct python version, it seems the library does not support https for registration urls.  See this line here as an example: 

https://github.com/SolarEdgeTech/pyctuator/blob/2536697fab1da3c77f2903f302d02909929903c2/pyctuator/impl/spring_boot_admin_registration.py#L70

Is there a way we can detect https vs http, or port 443 as an example, to change to use the HTTPSConnection connection?

Thanks!
Peter

**Comment by michaelyaakoby** [comment]
Hi Peter, 
That's a good question... 
Will look into this.
Thanks 
Michael

**Comment by PvanHengel** [comment]
Thank you happy to help where possible, it might make more sense to shift and use the requests library, not sure if there is a reason for using the lower level httpconnection over that?  I think it could handle both quite easily.

**Comment by michaelyaakoby** [comment]
You are right that using `requests` would be much easier, however our goal and requirement was to avoid using any library that's not really really really required.
I'm sure we'll find reasonable solution without requests - i'll probably get to dive into this later this week, however if you have a reasonable workaround that doesn't require adding a dependency, please issue a PR.
Thanks again,
Michael

**Comment by michaelyaakoby** [comment]
Fixed in v0.13.2
