### ISSUE TITLE
Python 3.6 support wanted

### ISSUE THREAD

**Issue by aneasystone** [SolarEdgeTech/pyctuator#42]
My project is using python 3.6, but pyctuator has a requirement Python 3.7+
I'm wondering if this requirement can be lower?

**Comment by michaelyaakoby** [comment]
Hi @aneasystone,
Pyctuator is a "heavy user" of dataclasses which were introduced in Python 3.7 which is the reason it requires Python 3.7 or above.
I suggest you'll try updating the Python you are using.
Michael
