### ISSUE TITLE
Feature Request: Adding optional information to the info endpoint.

### ISSUE THREAD

**Issue by mikand13** [SolarEdgeTech/pyctuator#50]
In our infrastructure we use custom elements of the info endpoint for among other things grafana links. Could you add a function for registering custom fields in the info endpoint?

**Comment by michaelyaakoby** [comment]
Hi @mikand13, I'm glad you are asking, because I think what you are asking for is already supported by Pyctuator but isn't documented too good - Pyctuator already lets you to provide a JSON value that's included in the registration.

Please see the comment in https://github.com/SolarEdgeTech/pyctuator/blob/master/pyctuator/pyctuator.py#L76 .
An example can be found at https://github.com/SolarEdgeTech/pyctuator/blob/a1e8ade496c5eb8987f49d11da3bd4e23b830411/tests/fast_api_test_server.py#L30

Can you please try it out and let us know how did it go.

Thanks,
Michael

**Comment by mikand13** [comment]
Ah, nice, will check!

**Comment by michaelyaakoby** [comment]
@mikand13 I'm closing this issue for now.
Please re-open with additional info if you need something different.
Thanks

**Comment by mikand13** [comment]
Hi, i didnt have a chance to test this until now. Been on vacation. As I understand it I would expect this to produce values in the /info endpoint?

        metadata=dict(
            serviceLinks=dict(
                metrics="url here"
            ),
            podLinks=dict(
                metrics="url here"
            )
        )

**Comment by mikand13** [comment]
Should be relatively easy to expose it in AppInfo?

            AppInfo(app=AppDetails(name=app_name, description=app_description)),

**Comment by michaelyaakoby** [comment]
Hi @mikand13,

While its possible to add an untyped parameter to `Pyctuator` that will be copied "as is" to the JSON returned from the `/actuator/info` - I prefer to follow our convention of declaring all the types.

Can you point me to the documentation of spring-actuator (or code) explaining what are the supported attribute so I can evaluate how bad it would be to explicitly support all of them.

Thanks,
Micahel

**Comment by mikand13** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints

2.10.2

Generally a direct manipulation of the json output.

**Comment by michaelyaakoby** [comment]
@mikand13 - moving the discussion/request to a dedicated issue, #53

**Comment by michaelyaakoby** [comment]
Ok, reopening the ticket - will post a suggestion soon.

**Comment by michaelyaakoby** [comment]
Testing this I added the info at the root of the `/pyctuator/info` URI so in SBA it looks like this:
![image](https://user-images.githubusercontent.com/5503849/128614376-df72bf25-e3f9-41f5-856b-6f07bd5014cb.png)

The JSON is:
```json
{
  "app": {
    "description": "Demonstrate Spring Boot Admin Integration with Flask",
    "name": "Flask Pyctuator"
  },
  "podLinks": {
    "metrics": "http://xyz/pod/metrics"
  },
  "serviceLinks": {
    "metrics": "http://xyz/service/metrics"
  }
}
```

@mikand13  is this what you were looking for?

**Comment by mikand13** [comment]
Looks perfect to me 👌

**Comment by michaelyaakoby** [comment]
Please upgrade to v0.14.0
