### ISSUE TITLE
Add option for custom SSL context for registration requests

### ISSUE THREAD

**Issue by deadpassive** [SolarEdgeTech/pyctuator#65]
There is currently no option to set the SSL context to use for registration requests. In my case this is required as my SBA server requires a valid certificate.

Looking at the code [here](https://github.com/SolarEdgeTech/pyctuator/blob/87f4e635fb558ec505008df47ca81112341ce83a/pyctuator/impl/spring_boot_admin_registration.py#L135) it doesn't look like it would be too difficult to pass in an SSL context to use for this in a similar way to `registration_auth`.

**Comment by michaelyaakoby** [comment]
Hi @deadpassive, indeed it should be easy adding an option to provide your own context.

Hope to get this done soon.

**Comment by michaelyaakoby** [comment]
@deadpassive , please take a look at #66 and tell me if that's what you need.

**Comment by michaelyaakoby** [comment]
Fixed in v0.16.0

**Comment by deadpassive** [comment]
Hi @michaelyaakoby - this looks exactly like what I need. Thanks for the swift response!
