### ISSUE TITLE
How do I secure pyctuator endpoints with basic auth (FastAPI)?

### ISSUE THREAD

**Issue by thurse93** [SolarEdgeTech/pyctuator#67]
In the API of the Pyctuator object I did not find a way to secure the provided endpoints with BasicAuth. What would be the most straightforward way of doing this using FastAPI?

Also, how can i communicate the credentials to Spring Boot Admin?

If I understood https://codecentric.github.io/spring-boot-admin/current/#spring-boot-admin-client right, I can use something like:

```
    metadata={
        "user.name": "foo",
        "user.password": "bar"
    }
```

In the metadata arg of Pyctuator. Is that correct?

**Comment by michaelyaakoby** [comment]
Your reference is for the java spring-boot-admin-client.
In Pyctuator, see https://github.com/SolarEdgeTech/pyctuator#spring-boot-admin-using-basic-authentication

**Comment by thurse93** [comment]
> Your reference is for the java spring-boot-admin-client. In Pyctuator, see https://github.com/SolarEdgeTech/pyctuator#spring-boot-admin-using-basic-authentication

Oh, I think there was a missunderstanding. I do not want to authenticate against a protected Spring Boot Admin Instance. Instead I want to secure the Endpoints of the App itself. Custom health providers could leak sensitive information, so I want some kind of BasicAuth-Mechanism for every route under `/pyctuator`.

**Comment by thurse93** [comment]
Hey @michaelyaakoby ,

100% agree with that. But atm securing the FastAPI endpoints normally happens on a per-endpoint / per-router basis, see: https://fastapi.tiangolo.com/advanced/security/http-basic-auth/ Since the Routing definition is taking place in pyctuator, the should be some kind of API to add at least the most basic kind of authentication.

More importantly, again referring to the spring boot admin docs: https://codecentric.github.io/spring-boot-admin/current/#_securing_client_actuator_endpoints
If I understand this section correctly SBA has builtin support for BasicAuth against the clients Endpoints. So on registration with SBA the client application can provide the metadata credentials (see https://codecentric.github.io/spring-boot-admin/current/#_sba_client / initial comment) needed for SBA to access its endpoints. If this is correct I think pyctuator should provide some kind of interface for this functionality.

**Comment by michaelyaakoby** [comment]
Oh, now I see the issue - reopening and lets try to find a way to configure FastAPI security using a "path" and not a specific function.

**Comment by michaelyaakoby** [comment]
Was a busy week, starting to dig now, will update.

**Comment by michaelyaakoby** [comment]
I've tidied up and completed the example in #70.
Once this will be reviewed, i'll merge and release.

**Comment by michaelyaakoby** [comment]
Done. 0.17.0
