### ISSUE TITLE
Problems encountered during registration

### ISSUE THREAD

**Issue by wlxgod** [SolarEdgeTech/pyctuator#78]
Hello, when I run it with python as below, the server returns 405 error, have you ever encountered this?
![e1131affbb768012b2d1ff2185ad0ac](https://user-images.githubusercontent.com/63198613/167289570-e09d876b-48d7-4f75-a07f-23efd0c90398.png)

![21051acbbf2943eff7b4a7fa2720ac7](https://user-images.githubusercontent.com/63198613/167289573-16bd3f38-f2d1-4caa-8191-be019f7b6989.png)

**Comment by wlxgod** [comment]
The url, password, and username shown in the image are correct

**Comment by michaelyaakoby** [comment]
Hi @wlxgod , the `regitration_url` should be the URL of your SBA (spring-boot-admin), is the value of `MONITOR_URL` is SBA's "/instances".

SBA exposes an endpoint for applications to register which is used by Pyctuator, so if your SBA is accessible via port 8080 of 1.2.3.4, the `registration_url` should be `http://1.2.3.4:8080/instances`.

You are getting 405 for "/monitor" so I suspect you are providing the wrong URL.

**Comment by wlxgod** [comment]
Thank you very much!!!
I have solved this problem!
