### ISSUE TITLE
Prometheus-endpoint: Are you planning to implement it?

### ISSUE THREAD

**Issue by jcarlosgalvezm** [SolarEdgeTech/pyctuator#80]
In the same way as in [Spring Boot Actuator](https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#prometheus), it would be interesting to have a /prometheus endpoint with the metrics in the format required for scraping by a Prometheus server. Are you planning to implement it?

Greetings and thanks in advance!

**Comment by michaelyaakoby** [comment]
Hi @jcarlosgalvezm ,
Its on my wish list to add endpoint for Prometheus to scrub.

A while a go I was looking for micrometer/prometheus libraries that we can integrate with so Pyctuator only needs to provide web interface (and not implementing the full blown meter-registry world).
Back then, I couldn't find mature implementations.

However, I think that changed and there are several libraries.
So, if you can research a bit around this and help choose a library that's mature and all is needed is web interface, yes we can do this.

Thanks,
M.

**Comment by michaelyaakoby** [comment]
@jcarlosgalvezm I went through prometheus's python-client and the do support simple integration with the common web servers and framework - see https://github.com/prometheus/client_python#exporting.

It seems to me that if prometheus's python-client is missing support for the web server/framework you are using, it should be added there instead.

**Comment by michaelyaakoby** [comment]
Closing this ticket - as mentioned above, a solution is already available from prometheus.
