### ISSUE TITLE
FastAPI 0.89.1 shows warning

### ISSUE THREAD

**Issue by NGEfreak** [SolarEdgeTech/pyctuator#87]
The following warning is shown using Pyctuator 1.0.1 and FastAPI 0.89.1:

```
fastapi\utils.py:88: RuntimeWarning: fields may not start with an underscore, ignoring "_links"
    return response_field(field_info=field_info)
```

FastAPI 0.89 has a new feature which uses the return annotation of a route to create the OpenAPI specification.

The warning is coming from this Pyctuator route:

https://github.com/SolarEdgeTech/pyctuator/blob/2b039ec2095df6f867cd0f6432bbdd0e4976222e/pyctuator/impl/fastapi_pyctuator.py#L45-L47

FastAPI converts the dataclass `EndpointsData` to a Pydantic model to create the OpenAPI specification. However, Pydantic doesn't allow fields starting with an underscore.

The simplest solution would be to set `response_model=None` in the route decorator:
```python
@router.get("/", include_in_schema=include_in_openapi_schema, tags=["pyctuator"], response_model=None)
def get_endpoints() -> EndpointsData:
    return self.get_endpoints_data()
```

This setting has precedence over the return annotation. In FastAPI 0.88 and earlier this was implicitly set to `None` and the return annotation was not used anyway.

Another solution would be to define `EndpointsData` as a Pydantic model with an alias definition:

```python
from pydantic import BaseModel, Field

class EndpointsData(BaseModel):
    links: EndpointsLinks = Field(..., alias="_links")
```

**Comment by michaelyaakoby** [comment]
Fixed in https://github.com/SolarEdgeTech/pyctuator/pull/91

**Comment by michaelyaakoby** [comment]
Version 1.0.2
