### ISSUE TITLE
How to add multiple databases Health Providers

### ISSUE THREAD

**Issue by mittal-umang** [SolarEdgeTech/pyctuator#96]
I have multiple Databases which need to be added to the health endpoint is there a way i can configure them.

**Comment by michaelyaakoby** [comment]
Hi,

So I verified this is supported in SBA, and it is.

For example, following the instructions in https://www.baeldung.com/spring-boot-configure-multiple-datasources, I've configured two datasources and, as you can watch their status in SBA:
![image](https://github.com/SolarEdgeTech/pyctuator/assets/5503849/79fb1be0-c3c0-4b87-a0ab-68956d9a76eb)

The actuator endpoint is showing the status of the two datasources as follows:
```json
{
  "status": "UP",
  "components": {
    "db": {
      "status": "UP",
      "components": {
        "todosDataSource": {
          "status": "UP",
          "details": {
            "database": "MySQL",
            "validationQuery": "isValid()"
          }
        },
        "topicsDataSource": {
          "status": "UP",
          "details": {
            "database": "MySQL",
            "validationQuery": "isValid()"
          }
        }
      }
    },
    . . .
}

```

Shouldn't be too hard to support calling `pyctuator.register_health_provider(...)` with two different engines as in:
```python
pyctuator.register_health_provider(DbHealthProvider(db_engine_1))
pyctuator.register_health_provider(DbHealthProvider(db_engine_2))
```

**Comment by michaelyaakoby** [comment]
The next release of pyctuator provides two solutions.

The first, a quick workaround, is to add two DB health-providers, each with its own unique name (the next release supports specifying provider's name):
```python
pyctuator.register_health_provider(DbHealthProvider(db_engine, "db1"))
pyctuator.register_health_provider(DbHealthProvider(db_engine, "db2"))
```

Which results with the following:
![image](https://github.com/SolarEdgeTech/pyctuator/assets/5503849/5b54c351-1503-4cb4-a3d2-7646c9aa535c)

However, the next release also supports "composite health provider" which allows you to group providers:
```python
pyctuator.register_health_provider(
    CompositeHealthProvider(
        "db",
        DbHealthProvider(db_engine, "db1"),
        DbHealthProvider(db_engine, "db2"),
    )
)
```
Which results with the following:
![image](https://github.com/SolarEdgeTech/pyctuator/assets/5503849/247903be-821a-4f21-b912-3d215d1c2dcf)

**Comment by michaelyaakoby** [comment]
Done.
Please upgrade to pyctuator 1.1.0
